#!/usr/bin/env python
from path import Path
import argparse
import re
import sys

parser = argparse.ArgumentParser(description="find missing files in a series of numbered files")
parser.add_argument('--path', default='.', help='directory to look for the serie')
parser.add_argument('--file_pattern', help='file pattern to match files againts ex: *.txt, help_*')
parser.add_argument('--include_dirs', action='store_true', help='include directories in files to match')
args = parser.parse_args()

d = Path(args.path)
file_list = d.files(args.file_pattern)
if args.include_dirs:
	file_list += d.dirs()
int_regex = re.compile('\d+')
#serie = [int(int_regex.search(f.name).group(0)) for f in file_list if int_regex.search(f.name)]
serie =[]
for f in file_list:
    m = int_regex.search(f.name)
    if m:
        serie.append(int(m.group(0)))

print  len(serie), max(serie)-min(serie),  len(serie)   *1.0 / (max(serie)-min(serie))
sys.exit(1)
try:
	not_in_serie = [i for i in xrange(min(serie),max(serie)) if i not in serie]
except ValueError:
	sys.exit(0)

for i in not_in_serie:
	print '{} not in serie'.format(i)
