#!/bin/bash

workspace=$(wmctrl -d |head -n1| awk -e '{
    if($2 == "*")
        print "0"
    else
        print "1"
}')

if [ $workspace -eq 0 ]; then
    if [ -S /home/fkalter/vlc.sock ]; then
        echo "pause" | nc -U /home/fkalter/vlc.sock
    elif [ "$(pidof parole)" ]; then
        parole --play
    fi
else
    parole --play
fi

echo "play/pause" | nc localhost 6007
