#!/bin/bash

# get current workspace
workspace=$(wmctrl -d |head -n1| awk -e '{
    if($2 == "*")
        print "0"
    else
        print "1"
}')

# "play" workspace with a main vlc player
if [ $workspace -eq 0 ]; then
    if [ -S /home/fkalter/vlc.sock ]; then
        echo "pause" | nc -U /home/fkalter/vlc.sock
    elif [ "$(pidof smplayer)" ]; then
        window_name=$(xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME | cut -d = -f 2 | sed 's/^ *//' | sed 's/^"//' | sed 's/"$//')
        smplayer -send-action play_or_pause
        wmctrl -a $window_name
    elif [ "$(pidof parole)" ]; then
        parole --play
    fi
# "work"  workspace with a parole player
elif [ "$(pidof parole)" ]; then
    parole --play
fi

# update stats to stathat.com
echo "play/pause" | nc localhost 6007
