#!/bin/bash

# get current workspace
workspace=$(wmctrl -d |head -n1| awk -e '{
    if($2 == "*")
        print "0"
    else
        print "1"
}')

# "play" workspace with a main vlc player
if [ $workspace -eq 0 ]; then
    if [ -S /home/fkalter/vlc.sock ]; then
        echo "pause" | nc -U /home/fkalter/vlc.sock
    elif [ "$(pidof parole)" ]; then
        parole --play
    elif [ "$(pidof smplayer)" ]; then
        current_window=$(xdotool getwindowfocus getwindowname)
        smplayer -send-action play_or_pause
        wmctrl -a $current_window
    fi
# "work"  workspace with a parole player
elif [ "$(pidof parole)" ]; then
    parole --play
fi

# update stats to stathat.com
echo "play/pause" | nc localhost 6007
