#!/home/fkalter/perl

use strict;
use warnings;
use 5.016000;
use File::ReadBackwards;

my $backwards = File::ReadBackwards->new("/home/fkalter/log.txt");
chomp(my $file = $backwards->readline);
$backwards->close();

system("trash-put \"$file\"");
system("~/scripts/vlc-random");
